# Build settings
markdown: kramdown

# Theme settings
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

# Site settings
title: Jeffrey Helt
description: "Computer Science PhD Student<br/>CS 314, Princeton University"
baseurl: ""
url: "www.jeffreyhelt.com"

# Social settings
email: jhelt@cs.princeton.edu
scholar_user: g4vbw9gAAAAJ
cv_path: /assets/cv.pdf
profile_photo_path: /assets/images/profile-photo.jpeg
